#!/bin/bash

FILE_TO_FIND=$1


function usage() {
  echo "usage: $(basename $0) <file_to_find>"
  echo "  <file_to_find>: name of a file that that will be search for from the current path."
  echo "  The first instance of the file will be diffed against the second."
  exit
}


if [ -z "$FILE_TO_FIND" ]; then
  usage()
fi


diff $(find . -name "$FILE_TO_FIND" -type f | head -1) $(find . -name "$FILE_TO_FIND" -type f | head -2 | tail -1)
