#!/bin/bash

## Watches by default the current directory, runs shellcheck on any files that change in the directory
## First argument is the folder to watch, by default is current folder.

while true; do 
  inotifywait -q -r -e modify --exclude=".swp" ${1:-.} --format "%w%f" | grep "sh$" | xargs --no-run-if-empty shellcheck
  date; 
done

